name: create deployment2

on:
  pull_request:
    branches: ["main", "develop"]
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  create-deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: tibdex/github-app-token@v1
      id: get_installation_token
      with: 
        app_id: 429906
        private_key: ${{ secrets.PRIVATE_KEY }}

    - uses: LouisBrunner/checks-action@v1.6.1
      if: github.event_name == 'pull_request'
      id: check
      with:
        sha: ${{ github.event.pull_request.head.sha }}
        token: ${{ steps.get_installation_token.outputs.token }}
        repo: JanLipovsekOrgTest/test_action_master
        # token: ${{ github.token }}
        name: Second Job
        status: in_progress
 
    - name: Trigger Workflow pr
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        github-token: ${{ steps.get_installation_token.outputs.token }}
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: 'JanLipovsekOrgTest',
            repo: 'test_action_slave',
            workflow_id: 'slave2.yml',
            ref: 'main',
            inputs: {
              "workflow-input-1": "${{ github.event.pull_request.head.sha }}",
              "workflow-input-2": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            }
          })
    - name: Trigger Workflow push
      if: github.event_name == 'push'
      uses: actions/github-script@v6
      with:
        github-token: ${{ steps.get_installation_token.outputs.token }}
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: 'JanLipovsekOrgTest',
            repo: 'test_action_slave',
            workflow_id: 'slave2.yml',
            ref: 'main',
            inputs: {
              "workflow-input-1": "//",
              "workflow-input-2": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            }
          })

    - uses: LouisBrunner/checks-action@v1.6.1
      if: failure() && github.event_name == 'pull_request'
      with:
        sha: ${{ github.event.pull_request.head.sha }}
        token: ${{ steps.get_installation_token.outputs.token }}
        repo: JanLipovsekOrgTest/test_action_master
        # token: ${{ github.token }}
        name: Second Job
        conclusion: ${{ job.status }}