name: create deployment2

on:
  pull_request:
    branches: [ "main" ]
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  create-deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: tibdex/github-app-token@v1
      id: get_installation_token
      with: 
        app_id: 429906
        private_key: ${{ secrets.PRIVATE_KEY }}

    - uses: LouisBrunner/checks-action@v1.6.1
      id: check
      with:
        sha: ${{ github.sha }}
        token: ${{ steps.get_installation_token.outputs.token }}
        repo: JanLipovsekOrgTest/test_action_master
        # token: ${{ github.token }}
        name: Second Job
        status: in_progress
 
    - name: test 3 Trigger Workflow ${{ github.sha }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ steps.get_installation_token.outputs.token }}
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: 'JanLipovsekOrgTest',
            repo: 'test_action_slave',
            workflow_id: 'slave2.yml',
            ref: 'main',
            inputs: {
              "workflow-input-1": "${{ github.sha }}",
              "workflow-input-2": "value-2",
            }
          })

    - uses: LouisBrunner/checks-action@v1.6.1
      if: failure()
      with:
        sha: ${{ github.sha }}
        token: ${{ steps.get_installation_token.outputs.token }}
        repo: JanLipovsekOrgTest/test_action_master
        # token: ${{ github.token }}
        name: Second Job
        conclusion: ${{ job.status }}