name: create deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  create-deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: tibdex/github-app-token@v1
      id: get_installation_token
      with: 
        app_id: 429906
        private_key: ${{ secrets.PRIVATE_KEY }}

    - uses: LouisBrunner/checks-action@v1.6.1
      id: check
      with:
        sha: ${{ github.sha }}
        token: ${{ steps.get_installation_token.outputs.token }}
        # token: ${{ github.token }}
        name: Second Job
        status: in_progress

    - name: Trigger Workflow
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.PAT}}
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: 'JanLipovsekOrgTest',
            repo: 'test_action_slave',
            workflow_id: 'slave.yml',
            ref: 'main',
            inputs: {
              "workflow-input-1": ${{ github.sha }},
              "workflow-input-2": "value-2",
            }
          })

    # - name: Dispatch an action and get the run ID
    #   uses: codex-/return-dispatch@v1
    #   id: return_dispatch
    #   with:
    #     token: ${{ secrets.PAT }} # Note this is NOT GITHUB_TOKEN but a PAT a
    #     ref: main # or refs/heads/target_branch
    #     repo: test_action_slave
    #     owner: JanLipovsekOrgTest
    #     workflow: slave.yml
    #     workflow_inputs: '{"workflow-input-1": "${{ github.sha }}", "workflow-input-2": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
    #     workflow_timeout_seconds: 300 # was 120  Default: 300

    - uses: LouisBrunner/checks-action@v1.6.1
      if: failure()
      with:
        sha: ${{ github.sha }}
        token: ${{ steps.get_installation_token.outputs.token }}
        # token: ${{ github.token }}
        name: Second Job
        conclusion: ${{ job.status }}
        details_url: https://josh-ops.com/posts/github-code-coverage/
        action_url: https://josh-ops.com/posts/github-code-coverage/
        output: |
          {"summary":""}
        #output_text_description_file: code-coverage-results.md